# FIX: https://github.com/microcmsio/nextjs-media-skeleton-template
name: Generate contents.json

on:
  push:
    branches:
      - release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Generate contents.json
        run: go run main.go
        working-directory: ./tools

      - name: Update contents.json
        run: |
          git config --local user.email "github-actions@example.com"
          git config --local user.name "github-actions"
          git add .
          git commit -m "Update contents.json"
          git push origin HEAD
